### ISSUE TITLE
Sidebar filters layout messed up 

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Windows-theme#186]
![image](https://user-images.githubusercontent.com/11031051/31308879-70290bae-ab86-11e7-9467-78b28ca3c873.png)

**Comment by chelkweber** [comment]
Can you elaborate on the issue, what should it look like?

**Comment by Jasius** [comment]
Hey, like this https://i.imgur.com/xjuSASD.png , it's bugged on FF.

**Comment by daviddeejjames** [comment]
Hi there, just wondering which version of Firefox? Seems fine on latest version (Firefox 56.0 on MacOS)

**Comment by Jasius** [comment]
Firefox developer edition(Quantum)
________________________________

**Comment by vikasverma93** [comment]
Hi, If you just want the buttons to be in one single line (), you can add `style="white-space: nowrap;"` to the parent list-item, or create a helper class `.text-nowrap { white-space: nowrap }` and add it to parent list-item. Since different browsers render fonts differently, Its just a matter of few pixels that last inline-block button is coming in next line.

**Comment by Jasius** [comment]
@vikasverma92 thanks, I'll look into this.

**Comment by Jasius** [comment]
Apparently it was new FF engine bug.
