### ISSUE TITLE
Leave the original flair button when a post is not flaired

### ISSUE THREAD

**Issue by sylveon** [Microsoft-community/Windows-theme#87]
I'm used to this button for flairing my posts:
![image](https://cloud.githubusercontent.com/assets/6440374/20869232/03cddb24-ba3c-11e6-9692-d48d39145543.png)

Well I can't see it anymore until I flair it:
![image](https://cloud.githubusercontent.com/assets/6440374/20869252/6690fb10-ba3c-11e6-93cc-e7d4f6abac08.png)
![image](https://cloud.githubusercontent.com/assets/6440374/20869258/854927b2-ba3c-11e6-9d3a-270595ab02fb.png)

**Comment by Jasius** [comment]
Hey,

It's been replaced by the actionable pop up which is visible in your second screenshot on the bottom left. On Reddit we're limited just to CSS so there had to be compromises for this feature. It was implemented because there's a tons of people who don't know how to flair their posts, this animated pop up makes it instantly noticeable in most scenarios.

Currently it will stay as it is but i may revisit it in the future.
